### PR TITLE
Support XEP-0114: Jabber Component Protocol

### PR DESCRIPTION
**Pull request by tsharju**
Hi,

Thanks for the awesome XMPP lib for Elixir. I'd need support for XEP-0114 and I though I'd send pull request your way.

Didn't add tests since it would need e.g., `ejabberd.yml` that would have the component connection configured. Are you planning to add one to the repo to be used with tests?

### CODE REVIEW

**Comment by scrogson** [comment]
Hey @tsharju, thanks for the kind words!

This is a fantastic idea to bring in XMPP components! It's something I've wanted to tackle, but haven't had the time to do.

I need some time to look over the code. At first glance I'm wondering if we should split things into they're own files? I realize that might cause a lot more duplication though. Hard to tell from the diff.

Really excited about this!

**Comment by tsharju** [comment]
Thanks for the feedback @scrogson. I've been rather busy lately. Yeah. I also thought about splitting it to different files but the component protocol is so very simple. It is basically starting a stream with certain namespace and then doing the handshake for authentication. And then you can basically start sending anything you want to the stream.

So that is basically what I did here. I added option to specify namespace for the `Romeo.Connection` and added handling for that namespace in `start_stream`. But yeah, definitely up for discussion how it could be done better. I'm currently using my own XMPP component implementation at https://github.com/futureflynet/jabber, but definitely would like to combine the efforts since it feels silly to write same stuff twice.

**Comment by scrogson** [comment]
@tsharju if you have time, would you mind resolving the conflict on this PR with `master`? After reviewing the code again, I think it's very close to being ready for a merge. There are a few tweaks I'd want to make though.

If you resolve the conflicts, I can merge it and make the code changes after. Otherwise, I can just incorporate your changes manually and author the commits with your email to give you credit.

Would either of these scenarios work for you?

**Comment by tsharju** [comment]
Thanks @scrogson. I can check the conflicts.

**Pull request merged**
